apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-creator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-creator-binding
  namespace: default
subjects:
- kind: User
  name: system:node:ip-172-31-0-126.ap-southeast-2.compute.internal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-creator
  apiGroup: rbac.authorization.k8s.io
